### ISSUE TITLE
Tests failing in Node v4

### ISSUE THREAD

**Issue by daffl** [donejs/done-serve#28]
Both, #26 and #27 are failing in Node 4 only because of the following error:

> Error: Error loading "basics-can@0.0.1#progressive/index.stache!done-autorender@1.0.0#src/autorender" at file:/Users/daffl/Jupiter/donejs/done-serve/test/tests/progressive/index.stache

> You can't have two versions of can-event/batch/batch, check your dependencies
    at Object.<anonymous> (file:/Users/daffl/Jupiter/donejs/done-serve/test/tests/node_modules/can-map/node_modules/can-event/batch/batch.js:575:8)
    at file:/Users/daffl/Jupiter/donejs/done-serve/test/tests/node_modules/can-map/node_modules/can-event/batch/batch.js:580:4
    at file:/Users/daffl/Jupiter/donejs/done-serve/test/tests/node_modules/can-map/node_modules/can-event/batch/batch.js:580:98
    at Object.exports.runInThisContext (vm.js:54:17)
    at doEval (/Users/daffl/Jupiter/donejs/done-serve/node_modules/done-ssr-middleware/node_modules/done-ssr/node_modules/steal/main.js:3823:10)
    at __eval (/Users/daffl/Jupiter/donejs/done-serve/node_modules/done-ssr-middleware/node_modules/done-ssr/node_modules/steal/main.js:3871:7)

**Comment by matthewp** [comment]
Will try to run it locally.
